name: Terraform AWS Deployment

on:
  push:
    branches:
      - feature

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VERSION: "1.5.7"  # Replace with your preferred Terraform version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"  # Replace with your preferred region

      # Remove the step for generating backend.tf if it already exists in your repository

      - name: Terraform Init 
        run: terraform init 

      - name: Terraform Workspace - Create and Select
        run: |
          terraform workspace new Staging || true
          terraform workspace select Staging

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        run: terraform plan -var-file=environments/staging.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=environments/staging.tfvars
