name: Terraform AWS Deployment and Docker Build/Push
on:
  push:
    branches:
      - feature

env:
  TF_VERSION: "1.5.7"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}


jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Init 
        run: |
          cd TerraformInfrastructure
          terraform init 

      - name: Terraform Workspace - Create and Select
        run: |
          cd TerraformInfrastructure
          terraform workspace new dev || true
          terraform workspace select dev

      - name: Terraform Validate
        run: |
          cd TerraformInfrastructure
          terraform validate 

      - name: Terraform Plan
        run: |
          cd TerraformInfrastructure
          terraform plan -var-file=environments/dev.tfvars
      - name: Terraform Apply or Destroy
        run: |
          cd TerraformInfrastructure
          terraform destroy -auto-approve -var-file=environments/dev.tfvars 

      
      # - name: Set Terraform Status
      #   id: set_terraform_status
      #   run: |
      #     TERRAFORM_STATUS=$(cat TerraformInfrastructure/terraform_action.txt)
      #     echo "::set-output name=terraform_status::$TERRAFORM_STATUS"

      

  build-and-push:
    needs: terraform-deploy
    runs-on: ubuntu-latest

    # if: ${{ needs.terraform-deploy.outputs['terraform-status'] != 'terraform destroy' }}
    
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          cd WebApplication
          python -m pip install --upgrade pip

      - name: Configure AWS credentials for Docker
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          cd WebApplication
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPO_URL }}
          docker build -t python-repo .
          docker tag python-repo:latest ${{ env.ECR_REPO_URL }}:latest
          docker push ${{ env.ECR_REPO_URL }}:latest

  trigger-pipeline:
    needs: build-and-push
    runs-on: ubuntu-latest

    # if: ${{ needs.terraform-deploy.outputs['terraform-status'] != 'terraform destroy' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials for CodePipeline
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Trigger CodePipeline
        run: |
          aws codepipeline start-pipeline-execution --name GuestAppPipeline
